// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct OrderForm {
    // message fields
    pub quantity: i32,
    pub product: OilProductType,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl OrderForm {
    pub fn new() -> OrderForm {
        ::std::default::Default::default()
    }

    // int32 quantity = 2;

    pub fn clear_quantity(&mut self) {
        self.quantity = 0;
    }

    // Param is passed by value, moved
    pub fn set_quantity(&mut self, v: i32) {
        self.quantity = v;
    }

    pub fn get_quantity(&self) -> i32 {
        self.quantity
    }

    // .refinery.OilProductType product = 3;

    pub fn clear_product(&mut self) {
        self.product = OilProductType::GASOLINE;
    }

    // Param is passed by value, moved
    pub fn set_product(&mut self, v: OilProductType) {
        self.product = v;
    }

    pub fn get_product(&self) -> OilProductType {
        self.product
    }
}

impl ::protobuf::Message for OrderForm {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.quantity = tmp;
                },
                3 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.product, 3, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.quantity != 0 {
            my_size += ::protobuf::rt::value_size(2, self.quantity, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.product != OilProductType::GASOLINE {
            my_size += ::protobuf::rt::enum_size(3, self.product);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.quantity != 0 {
            os.write_int32(2, self.quantity)?;
        }
        if self.product != OilProductType::GASOLINE {
            os.write_enum(3, self.product.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OrderForm {
        OrderForm::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "quantity",
                    |m: &OrderForm| { &m.quantity },
                    |m: &mut OrderForm| { &mut m.quantity },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<OilProductType>>(
                    "product",
                    |m: &OrderForm| { &m.product },
                    |m: &mut OrderForm| { &mut m.product },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<OrderForm>(
                    "OrderForm",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static OrderForm {
        static mut instance: ::protobuf::lazy::Lazy<OrderForm> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const OrderForm,
        };
        unsafe {
            instance.get(OrderForm::new)
        }
    }
}

impl ::protobuf::Clear for OrderForm {
    fn clear(&mut self) {
        self.clear_quantity();
        self.clear_product();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OrderForm {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OrderForm {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct OrderStatus {
    // message fields
    pub status: OrderResponseType,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl OrderStatus {
    pub fn new() -> OrderStatus {
        ::std::default::Default::default()
    }

    // .refinery.OrderResponseType status = 1;

    pub fn clear_status(&mut self) {
        self.status = OrderResponseType::UNKNOWN;
    }

    // Param is passed by value, moved
    pub fn set_status(&mut self, v: OrderResponseType) {
        self.status = v;
    }

    pub fn get_status(&self) -> OrderResponseType {
        self.status
    }
}

impl ::protobuf::Message for OrderStatus {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.status, 1, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.status != OrderResponseType::UNKNOWN {
            my_size += ::protobuf::rt::enum_size(1, self.status);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.status != OrderResponseType::UNKNOWN {
            os.write_enum(1, self.status.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OrderStatus {
        OrderStatus::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<OrderResponseType>>(
                    "status",
                    |m: &OrderStatus| { &m.status },
                    |m: &mut OrderStatus| { &mut m.status },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<OrderStatus>(
                    "OrderStatus",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static OrderStatus {
        static mut instance: ::protobuf::lazy::Lazy<OrderStatus> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const OrderStatus,
        };
        unsafe {
            instance.get(OrderStatus::new)
        }
    }
}

impl ::protobuf::Clear for OrderStatus {
    fn clear(&mut self) {
        self.clear_status();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OrderStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OrderStatus {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum OilProductType {
    GASOLINE = 0,
    JETFUEL = 1,
    DIESEL = 2,
    ASPHALT = 3,
    HEAVY = 4,
    LUBRICANT = 5,
    OTHER = 6,
}

impl ::protobuf::ProtobufEnum for OilProductType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<OilProductType> {
        match value {
            0 => ::std::option::Option::Some(OilProductType::GASOLINE),
            1 => ::std::option::Option::Some(OilProductType::JETFUEL),
            2 => ::std::option::Option::Some(OilProductType::DIESEL),
            3 => ::std::option::Option::Some(OilProductType::ASPHALT),
            4 => ::std::option::Option::Some(OilProductType::HEAVY),
            5 => ::std::option::Option::Some(OilProductType::LUBRICANT),
            6 => ::std::option::Option::Some(OilProductType::OTHER),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [OilProductType] = &[
            OilProductType::GASOLINE,
            OilProductType::JETFUEL,
            OilProductType::DIESEL,
            OilProductType::ASPHALT,
            OilProductType::HEAVY,
            OilProductType::LUBRICANT,
            OilProductType::OTHER,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("OilProductType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for OilProductType {
}

impl ::std::default::Default for OilProductType {
    fn default() -> Self {
        OilProductType::GASOLINE
    }
}

impl ::protobuf::reflect::ProtobufValue for OilProductType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum OrderResponseType {
    UNKNOWN = 0,
    RECEIVED = 1,
    REJECTED = 2,
}

impl ::protobuf::ProtobufEnum for OrderResponseType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<OrderResponseType> {
        match value {
            0 => ::std::option::Option::Some(OrderResponseType::UNKNOWN),
            1 => ::std::option::Option::Some(OrderResponseType::RECEIVED),
            2 => ::std::option::Option::Some(OrderResponseType::REJECTED),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [OrderResponseType] = &[
            OrderResponseType::UNKNOWN,
            OrderResponseType::RECEIVED,
            OrderResponseType::REJECTED,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("OrderResponseType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for OrderResponseType {
}

impl ::std::default::Default for OrderResponseType {
    fn default() -> Self {
        OrderResponseType::UNKNOWN
    }
}

impl ::protobuf::reflect::ProtobufValue for OrderResponseType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0erefinery.proto\x12\x08refinery\x1a\x1fgoogle/protobuf/timestamp.pr\
    oto\"[\n\tOrderForm\x12\x1a\n\x08quantity\x18\x02\x20\x01(\x05R\x08quant\
    ity\x122\n\x07product\x18\x03\x20\x01(\x0e2\x18.refinery.OilProductTypeR\
    \x07product\"B\n\x0bOrderStatus\x123\n\x06status\x18\x01\x20\x01(\x0e2\
    \x1b.refinery.OrderResponseTypeR\x06status*i\n\x0eOilProductType\x12\x0c\
    \n\x08GASOLINE\x10\0\x12\x0b\n\x07JETFUEL\x10\x01\x12\n\n\x06DIESEL\x10\
    \x02\x12\x0b\n\x07ASPHALT\x10\x03\x12\t\n\x05HEAVY\x10\x04\x12\r\n\tLUBR\
    ICANT\x10\x05\x12\t\n\x05OTHER\x10\x06*<\n\x11OrderResponseType\x12\x0b\
    \n\x07UNKNOWN\x10\0\x12\x0c\n\x08RECEIVED\x10\x01\x12\x0c\n\x08REJECTED\
    \x10\x022?\n\x08Refinery\x123\n\x05Order\x12\x13.refinery.OrderForm\x1a\
    \x15.refinery.OrderStatusb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
