# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

# We'd like to use `diesel-derive-enum`. The crate doesn't support infer_schema!
# Commenting this out so diesel cli doesn't overwrite.
#[print_schema]
#file = "models/schema.rs"
