[workspace]

members = [
  "cli-clap",
  "docker-shiplift",
  "nsq",
  "redis",
  "vault",
  "cli-grpc-tonic-blocking"
]

exclude = [
  "cli-clap-grpc-pingcap-db-diesel",
  "consul",
  "db-diesel-postgres",
  "grpc-pingcap",
]