[package]
name = "proc-macro-attribute"
version = "0.1.0"
authors = ["T.J. Telan <t.telan@gmail.com>"]
edition = "2018"

[workspace]

[[bin]]
name = "proc-macros"
path = "main.rs"

[dependencies]
attribute-macro = { path = "attribute-macro"}
