version: '3'
services:
  vault:
    image: vault:1.3.0
    container_name: vault
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=test
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command:
      - vault
      - server
      - -dev-kv-v1
